/*
	NAME : 		LS maps (exterior)
	DESC :		Some maps in LS.
	AUTHOR : 	Gigistone
*/


	gobj = CreateDynamicObject(3077,1800.387,-1864.347,12.472,0.000,0.000,0.000,-1,-1,-1,90.000,90.000);
	SetDynamicObjectMaterial(gobj, 1, 2589, "ab_ab", "ab_sheetSteel", 0);
	SetDynamicObjectMaterial(gobj, 0, 19171, "gtamap", "GTASAMapBit4", 0);
	gobj = CreateDynamicObject(3077,1629.500,-2330.764,12.443,0.000,0.000,0.000,-1,-1,-1,90.000,90.000);
	SetDynamicObjectMaterial(gobj, 1, 2589, "ab_ab", "ab_sheetSteel", 0);
	SetDynamicObjectMaterial(gobj, 0, 19171, "gtamap", "GTASAMapBit4", 0);
	gobj = CreateDynamicObject(3077,815.318,-1337.343,12.441,0.000,0.000,0.000,-1,-1,-1,90.000,90.000);
	SetDynamicObjectMaterial(gobj, 1, 2589, "ab_ab", "ab_sheetSteel", 0);
	SetDynamicObjectMaterial(gobj, 0, 19171, "gtamap", "GTASAMapBit4", 0);
	gobj = CreateDynamicObject(3077,1187.171,-1369.021,12.443,0.000,0.000,90.000,-1,-1,-1,90.000,90.000);
	SetDynamicObjectMaterial(gobj, 1, 2589, "ab_ab", "ab_sheetSteel", 0);
	SetDynamicObjectMaterial(gobj, 0, 19171, "gtamap", "GTASAMapBit4", 0);
	gobj = CreateDynamicObject(3077,385.296,-1600.141,28.595,0.000,0.000,-0.059,-1,-1,-1,90.000,90.000);
	SetDynamicObjectMaterial(gobj, 1, 2589, "ab_ab", "ab_sheetSteel", 0);
	SetDynamicObjectMaterial(gobj, 0, 19171, "gtamap", "GTASAMapBit4", 0);
	gobj = CreateDynamicObject(3077,572.671,-1245.395,16.347,0.000,0.000,25.000,-1,-1,-1,90.000,90.000);
	SetDynamicObjectMaterial(gobj, 1, 2589, "ab_ab", "ab_sheetSteel", 0);
	SetDynamicObjectMaterial(gobj, 0, 19171, "gtamap", "GTASAMapBit4", 0);